apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: drkiq-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: drkiq
    spec:
      containers:
      - name: drkiq
        image: salahkhaled101/drkiq:fin
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: drkiq-configmap
        volumeMounts:
        - mountPath: /drkiq/public
          name: drkiq-volume
      volumes:
        - name: drkiq-volume
          persistentVolumeClaim:
            claimName: drkiq-pvc

