apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: drkiq-ing
spec:
  rules:
     - http:
         paths:
          - path: /
            backend:
              serviceName: drkiq
              servicePort: 8000

